### ISSUE TITLE
Wildcard fout triggert stacktracemail

### ISSUE THREAD

**Issue by phavekes** [OpenConext/OpenConext-manage#176]
[This issue is imported from pivotal - Originaly created at May 8, 2018 by Thijs Kinkhorst](https://www.pivotaltracker.com/story/show/157387598)

Als iemand bij het zoeken een wildcardfout maakt krijg ik een mail met een stacktrace:

```
java.util.regex.PatternSyntaxException: Unclosed group near index 22 .*RIS (Acceptatie NG.* ^
    at java.util.regex.Pattern.error(Pattern.java:1955)
    at java.util.regex.Pattern.accept(Pattern.java:1813)
    at java.util.regex.Pattern.group0(Pattern.java:2908)
    at java.util.regex.Pattern.sequence(Pattern.java:2051)
    at java.util.regex.Pattern.expr(Pattern.java:1996)
    at java.util.regex.Pattern.compile(Pattern.java:1696)
    at java.util.regex.Pattern.<init>(Pattern.java:1351)
    at java.util.regex.Pattern.compile(Pattern.java:1054)
    at org.springframework.data.mongodb.core.query.Criteria.toPattern(Criteria.java:404)
    at org.springframework.data.mongodb.core.query.Criteria.regex(Criteria.java:379)
    at manage.repository.MetaDataRepository.regex(MetaDataRepository.java:71)
    at manage.repository.MetaDataRepository.autoComplete(MetaDataRepository.java:64)
    at manage.repository.MetaDataRepository$$FastClassBySpringCGLIB$$ff6a4e74.invoke(<generated>) 
```

Ivm broken window syndrome niet zo nuttig; in de app zelf afhandelen heeft de voorkeur.

**Comment by phavekes** [comment]
Deployed on test2. (Okke Harsta - May 11, 2018)
