### ISSUE TITLE
Manage ACC won\'t start

### ISSUE THREAD

**Issue by phavekes** [OpenConext/OpenConext-manage#358]
[This issue is imported from pivotal - Originaly created at Mar 8, 2022 by Okke Harsta](https://www.pivotaltracker.com/story/show/181495272)

2022-03-08 09:43:19,665 INFO [main] manage.Application:55 - Starting Application v7.0.0 using Java 11.0.14 on japp1.acc.ams.surfconext.nl with PID 19632 (/opt/manage/manage-server-7.0.0.jar started by manage in /opt/manage)
2022-03-08 09:43:19,677 INFO [main] manage.Application:637 - No active profile set, falling back to default profiles: default
2022-03-08 09:43:22,796 INFO [main] manage.conf.MetaDataAutoConfiguration:77 - Finished loading 5 metadata configurations
2022-03-08 09:43:23,269 INFO [main] o.s.s.web.DefaultSecurityFilterChain:51 - Will secure Ant [pattern=\'/client/users/disclaimer\'] with []
2022-03-08 09:43:23,271 INFO [main] o.s.s.web.DefaultSecurityFilterChain:51 - Will secure Ant [pattern=\'/internal/health\'] with []
2022-03-08 09:43:23,271 INFO [main] o.s.s.web.DefaultSecurityFilterChain:51 - Will secure Ant [pattern=\'/internal/info\'] with []
2022-03-08 09:43:23,304 INFO [main] o.s.s.web.DefaultSecurityFilterChain:51 - Will secure Or [Ant [pattern=\'/client/**\']] with [org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@50194e8d, org.springframework.security.web.context.SecurityContextPersistenceFilter@16073fa8, org.springframework.security.web.header.HeaderWriterFilter@1aa99005, manage.web.SessionAliveFilter@3cee53dc, org.springframework.security.web.csrf.CsrfFilter@3e1624c7, manage.web.CsrfTokenResponseHeaderBindingFilter@290aeb20, org.springframework.security.web.authentication.logout.LogoutFilter@5c82cd4f, org.springframework.security.web.authentication.www.BasicAuthenticationFilter@73ad4ecc, manage.shibboleth.ShibbolethPreAuthenticatedProcessingFilter@69da0b12, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@cfbc8e8, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@46d9aec8, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@2764c546, org.springframework.security.web.session.SessionManagementFilter@3cd59ef5, org.springframework.security.web.access.ExceptionTranslationFilter@776802b0, org.springframework.security.web.access.intercept.FilterSecurityInterceptor@5411dd90]
2022-03-08 09:43:23,307 INFO [main] o.s.s.web.DefaultSecurityFilterChain:51 - Will secure Ant [pattern=\'/internal/**\'] with [org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@3b05a99b, org.springframework.security.web.context.SecurityContextPersistenceFilter@45d6ef73, org.springframework.security.web.header.HeaderWriterFilter@a52ca2e, org.springframework.security.web.authentication.logout.LogoutFilter@314c8b4a, org.springframework.security.web.authentication.www.BasicAuthenticationFilter@2c43eb8, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@3f29e26, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@1f6d27cc, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@7d0cc890, org.springframework.security.web.session.SessionManagementFilter@1ad8df52, org.springframework.security.web.access.ExceptionTranslationFilter@bb9ab64, org.springframework.security.web.access.intercept.FilterSecurityInterceptor@5cbd159f]
2022-03-08 09:43:23,828 INFO [main] manage.Application:61 - Started Application in 5.024 seconds (JVM running for 5.495)
2022-03-08 09:43:23,993 ERROR [main] c.g.c.m.r.c.executor.MongockRunnerBase:69 - Error in mongock process. ABORTED MIGRATION
com.github.cloudyrock.mongock.exception.MongockException: com.mongodb.MongoQueryException: Query failed with error code 148 and error message \'Storage engine does not support read concern: { readConcern: { level: "majority" } }\' on server db3.mongo.acc.surfconext.nl:27017
	at com.github.cloudyrock.mongock.runner.core.executor.MongockRunnerBase.execute(MongockRunnerBase.java:68)
	at com.github.cloudyrock.spring.v5.MongockSpring5$MongockApplicationRunner.run(MongockSpring5.java:68)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:760)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:750)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:309)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292)
	at manage.Application.main(Application.java:20)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: com.mongodb.MongoQueryException: Query failed with error code 148 and error message \'Storage engine does not support read concern: { readConcern: { level: "majority" } }\' on server db3.mongo.acc.surfconext.nl:27017
	at com.mongodb.internal.operation.FindOperation.lambda$execute$1(FindOperation.java:670)
	at com.mongodb.internal.operation.OperationHelper.lambda$withSourceAndConnection$2(OperationHelper.java:564)
	at com.mongodb.internal.operation.OperationHelper.withSuppliedResource(OperationHelper.java:589)
	at com.mongodb.internal.operation.OperationHelper.lambda$withSourceAndConnection$3(OperationHelper.java:563)
	at com.mongodb.internal.operation.OperationHelper.withSuppliedResource(OperationHelper.java:589)
	at com.mongodb.internal.operation.OperationHelper.withSourceAndConnection(OperationHelper.java:562)
	at com.mongodb.internal.operation.FindOperation.lambda$execute$2(FindOperation.java:661)
	at com.mongodb.internal.async.function.RetryingSyncSupplier.get(RetryingSyncSupplier.java:65)
	at com.mongodb.internal.operation.FindOperation.execute(FindOperation.java:692)
	at com.mongodb.internal.operation.FindOperation.execute(FindOperation.java:86)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:191)
	at com.mongodb.client.internal.FindIterableImpl.first(FindIterableImpl.java:200)
	at com.github.cloudyrock.mongock.driver.mongodb.sync.v4.repository.MongoSync4ChangeEntryRepository.isAlreadyExecuted(MongoSync4ChangeEntryRepository.java:55)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.isAlreadyExecuted(MigrationExecutor.java:135)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.lambda$isThereAnyChangeSetItemToBeExecuted$3(MigrationExecutor.java:131)
	at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1632)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:278)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.TreeMap$KeySpliterator.tryAdvance(TreeMap.java:2763)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:528)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.isThereAnyChangeSetItemToBeExecuted(MigrationExecutor.java:131)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.executeMigration(MigrationExecutor.java:65)
	at com.github.cloudyrock.spring.v5.core.SpringMigrationExecutor.executeMigration(SpringMigrationExecutor.java:37)
	at com.github.cloudyrock.mongock.runner.core.executor.MongockRunnerBase.execute(MongockRunnerBase.java:53)
	... 15 common frames omitted
2022-03-08 09:43:24,028 ERROR [main] o.springframework.boot.SpringApplication:821 - Application run failed
java.lang.IllegalStateException: Failed to execute ApplicationRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:763)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:750)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:309)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292)
	at manage.Application.main(Application.java:20)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: com.github.cloudyrock.mongock.exception.MongockException: com.mongodb.MongoQueryException: Query failed with error code 148 and error message \'Storage engine does not support read concern: { readConcern: { level: "majority" } }\' on server db3.mongo.acc.surfconext.nl:27017
	at com.github.cloudyrock.mongock.runner.core.executor.MongockRunnerBase.execute(MongockRunnerBase.java:68)
	at com.github.cloudyrock.spring.v5.MongockSpring5$MongockApplicationRunner.run(MongockSpring5.java:68)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:760)
	... 13 common frames omitted
Caused by: com.mongodb.MongoQueryException: Query failed with error code 148 and error message \'Storage engine does not support read concern: { readConcern: { level: "majority" } }\' on server db3.mongo.acc.surfconext.nl:27017
	at com.mongodb.internal.operation.FindOperation.lambda$execute$1(FindOperation.java:670)
	at com.mongodb.internal.operation.OperationHelper.lambda$withSourceAndConnection$2(OperationHelper.java:564)
	at com.mongodb.internal.operation.OperationHelper.withSuppliedResource(OperationHelper.java:589)
	at com.mongodb.internal.operation.OperationHelper.lambda$withSourceAndConnection$3(OperationHelper.java:563)
	at com.mongodb.internal.operation.OperationHelper.withSuppliedResource(OperationHelper.java:589)
	at com.mongodb.internal.operation.OperationHelper.withSourceAndConnection(OperationHelper.java:562)
	at com.mongodb.internal.operation.FindOperation.lambda$execute$2(FindOperation.java:661)
	at com.mongodb.internal.async.function.RetryingSyncSupplier.get(RetryingSyncSupplier.java:65)
	at com.mongodb.internal.operation.FindOperation.execute(FindOperation.java:692)
	at com.mongodb.internal.operation.FindOperation.execute(FindOperation.java:86)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:191)
	at com.mongodb.client.internal.FindIterableImpl.first(FindIterableImpl.java:200)
	at com.github.cloudyrock.mongock.driver.mongodb.sync.v4.repository.MongoSync4ChangeEntryRepository.isAlreadyExecuted(MongoSync4ChangeEntryRepository.java:55)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.isAlreadyExecuted(MigrationExecutor.java:135)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.lambda$isThereAnyChangeSetItemToBeExecuted$3(MigrationExecutor.java:131)
	at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1632)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:278)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.TreeMap$KeySpliterator.tryAdvance(TreeMap.java:2763)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:528)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.isThereAnyChangeSetItemToBeExecuted(MigrationExecutor.java:131)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.executeMigration(MigrationExecutor.java:65)
	at com.github.cloudyrock.spring.v5.core.SpringMigrationExecutor.executeMigration(SpringMigrationExecutor.java:37)
	at com.github.cloudyrock.mongock.runner.core.executor.MongockRunnerBase.execute(MongockRunnerBase.java:53)
	... 15 common frames omitted

**Comment by phavekes** [comment]
Fixed by Bart. enableMajorityReadConcern set to true. (Okke Harsta - Mar 8, 2022)
