### ISSUE TITLE
Report which metadatafields fail validation

### ISSUE THREAD

**Issue by phavekes** [OpenConext/OpenConext-manage#391]
[This issue is imported from pivotal - Originaly created at Mar 15, 2024 by Bart Geesink](https://www.pivotaltracker.com/story/show/187245373)

When a metadata json is posted to the API, it might happen that the validation fails. An error is raised, wich contains:
org.everit.json.schema.ValidationException: #/metaDataFields: 2 schema violations found 

The error does not mention which fields violate the schema. It would help the debugging proces if the error includes which fields fail validation

**Comment by phavekes** [comment]
```
manage.exception.CustomValidationException: org.everit.json.schema.ValidationException: #/metaDataFields: 3 schema violations found, #/metaDataFields: required key [name:en] not found, #/metaDataFields: required key [AssertionConsumerService:0:Binding] not found, #/metaDataFields: required key [AssertionConsumerService:0:Location] not found
	at manage.conf.MetaDataAutoConfiguration.validate(MetaDataAutoConfiguration.java:95)
	at manage.service.MetaDataService.validate(MetaDataService.java:554)
	at manage.service.MetaDataService.doPost(MetaDataService.java:193)
	at manage.control.MetaDataController.postInternal(MetaDataController.java:120)

``` (Okke Harsta - Mar 15, 2024)
