### ISSUE TITLE
Change requests diff fails on TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by phavekes** [OpenConext/OpenConext-manage#414]
[This issue is imported from pivotal - Originaly created at Jul 9, 2024 by Okke Harsta](https://www.pivotaltracker.com/story/show/187926311)

```
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at re (main.c89d1df7.js:2:1884610)
    at main.c89d1df7.js:2:3191958
    at Array.reduce (<anonymous>)
    at main.c89d1df7.js:2:3191924
    at aO.renderDiff (main.c89d1df7.js:2:3191976)
    at aO.renderChangeRequestTable (main.c89d1df7.js:2:3193937)
    at main.c89d1df7.js:2:3195861
    at Array.map (<anonymous>)
    at aO.render (main.c89d1df7.js:2:3195844)
re @ main.c89d1df7.js:2
(anonymous) @ main.c89d1df7.js:2
(anonymous) @ main.c89d1df7.js:2
renderDiff @ main.c89d1df7.js:2
renderChangeRequestTable @ main.c89d1df7.js:2
(anonymous) @ main.c89d1df7.js:2
render @ main.c89d1df7.js:2
```

**Comment by phavekes** [comment]
https://github.com/OpenConext/OpenConext-manage/actions/runs/9851882071 (Okke Harsta - Jul 9, 2024)
