### ISSUE TITLE
Unexpected error is not quite unexpected

### ISSUE THREAD

**Issue by baszoetekouw** [OpenConext/OpenConext-manage#449]
Manage sends exceptions like this:
```
org.everit.json.schema.ValidationException: #: Not allowed to configure 'coin:stepup:requireloa'. This SP is already configured as a stepupEntity in IdP: http://login.surf.nl/adfs/services/trust
    at manage.hook.SSIDValidationHook.validate(SSIDValidationHook.java:59)
    at manage.hook.SSIDValidationHook.prePut(SSIDValidationHook.java:37)
    at manage.hook.CompositeMetaDataHook.lambda$prePut$2(CompositeMetaDataHook.java:33)
    at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) 
```
even though this exception is already handled correctly in UI, and is not unexpected at all.  

Could you disable the sending of mails for this exception?

**Comment by baszoetekouw** [comment]
Same for this one:
```
org.everit.json.schema.ValidationException: #: No data is changed. An update would result in an empty revision
    at manage.hook.EmptyRevisionHook.prePut(EmptyRevisionHook.java:32)
    at manage.hook.CompositeMetaDataHook.lambda$prePut$2(CompositeMetaDataHook.java:33)
    at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
    at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
    at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) 
```

**Comment by oharsta** [comment]
Use
```
        <dependency>
            <groupId>org.openconext</groupId>
                <artifactId>threshold-logger</artifactId>
            <version>2.0.1</version>
        </dependency>

```
